### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/quickbook#17]
Here:
https://github.com/boostorg/quickbook/blob/5f2e8c24cb813b4b0b94d3316e664b971c5b71dd/src/parsers.hpp#L81

Warning:
```
\quickbook\src\parsers.hpp(81): warning C4709: comma operator within array index expression
```

Compiling with VS2019

**Comment by Kojoley** [comment]
This warning is broken in MSVC for ages https://developercommunity.visualstudio.com/t/buggy-warning-c4709/471956

**Comment by vinniefalco** [comment]
Can we work around it or something, to stop it from warning?

**Comment by Kojoley** [comment]
> Can we work around it or something, to stop it from warning?

Please check #20 whether it helps or not.
